import { driveNames } from "@/lib/core-utils/fit-core";


export type DriveName = (typeof driveNames)[number];

export const DRAIN_ADVICE: Record<DriveName, Partial<Record<DriveName, string>>> = {
    Exploration: {
    Achievement: `You may be investing a lot of energy in exploring new ideas and possibilities with the hope that the right insight will finally unlock the progress and achievement you care about. In this pattern, exploration can feel productive without requiring the constraints that achievement demands—deadlines, narrowing scope, and tolerating imperfect execution. The strain arises when curiosity keeps expanding but your “achievement meter” still doesn’t move, so exploration starts to feel more like busywork than growth. A reassuring balance is to keep exploration, while routinely converting it into one concrete deliverable at a time—a prototype, draft, submission, demo, or measurable milestone. That way, exploration becomes the fuel for achievement rather than a detour around it.`,
    Dominance: `You may explore new ideas partly to gain a sense of control—believing that the person with the most compelling idea gets to shape the direction and call the shots. This can quietly turn exploration into a leadership strategy: collecting novelty to justify authority. The strain shows up when reality stays unpredictable even with great ideas, leaving you anxious and still not truly “in charge.” A healthier approach is to separate insight from control: use exploration to identify a few levers you can actually influence, then take small decisive actions within that scope. This turns exploration from status-seeking into a grounded sense of authority over your own choices.`,
    Pleasure: `You may chase novelty and stimulation to compensate for difficulty accessing genuine pleasure or rest. When pleasure feels unavailable, exploration can become a substitute—new topics, new plans, new rabbit holes—so you don’t have to sit with boredom, emptiness, or fatigue. The strain is that novelty eventually stops restoring you and begins to feel like restlessness you can’t turn off. A supportive balance is to introduce intentional pleasure—sensory comfort, play, recovery, unstructured downtime—that doesn’t have to be earned through constant discovery. When pleasure is treated as legitimate, exploration becomes joyful again rather than compulsive.`,
    Care: `You may pour energy into understanding people, psychology, or relationship dynamics in hopes that insight will compensate for unmet needs in intimacy—whether with a partner or close family. This can create “over-analysis caregiving,” where thinking replaces direct emotional contact and repair. The strain appears when you feel you’ve “figured everything out,” yet the relationship still lacks warmth, security, or reciprocity. A better balance is to reduce interpretation and increase simple care behaviors: consistency, reassurance, listening, and direct acts of support. Care is often satisfied more by presence and reliability than by explanation.`,
    Affiliation: `You may pursue new experiences and ideas as a route to belonging—hoping that being interesting, informed, or adventurous will naturally create social connection. In this pattern, exploration becomes social currency: “If I keep bringing novelty, I’ll stay included.” The strain is that affiliation remains thin, because closeness depends more on repetition, trust, and mutual investment than on novelty. A balanced approach is to keep exploration, but also build rituals of belonging: regular contact, shared commitments, and showing up even when you have nothing new to offer. Then affiliation becomes stable and safe, not something you have to perform.`,
    Value: `You may hold a value system where being inventive and explorative feels like a treasured trait—believing that being a “cool innovator” will meet the expectations of society or family. When constant searching doesn’t translate into outcomes that satisfy your internal standard, you may start to devalue yourself, as if exploration only counts when it produces a discovery. The strain is that your sense of worth becomes dependent on exceptional originality, which is an exhausting bar to live under. A healthier balance is to re-evaluate whether you must make new discoveries to be valuable and to widen your definition of contribution. Many forms of impact—mentorship, craftsmanship, service, steady improvement, and relational support—are also meaningful and worthy.`,
  },

  Achievement: {
    Exploration: `You may pursue goals and output as a way to “earn” the right to explore—treating curiosity like a reward instead of a basic psychological nutrient. This can keep you in performance mode even when learning, novelty, and play would actually restore your motivation and clarity. The strain often shows up as burnout or dullness: you keep on trying to achieve goals, yet you feel mentally flat and less inspired over time. A supportive balance is to treat exploration as an input to achievement. Protect time for learning, experimentation, and open-ended curiosity. When exploration is scheduled proactively, achievement becomes more creative, sustainable, and less brittle.`,
    Dominance: `You may chase achievement to compensate for feeling powerless—believing that success will secure respect, influence, or safety. This can create a pressure loop: the more control you want, the more you over-invest in outcomes and feel like you can’t afford to slow down. The strain is that achievement rarely produces lasting dominance; it offers temporary wins, but the underlying uncertainty can remain. A healthier approach is to build direct agency alongside your goals: clarify authority, negotiate boundaries, and choose arenas where you truly have leverage. That way your sense of control comes from structure and positioning, not only from results.`,
    Pleasure: `You may invest heavily in achievement hoping it will eventually unlock peace, joy, or permission to rest. But when pleasure is postponed until after success, it often stays out of reach—because there is always another milestone. The strain can look like anhedonia: you accomplish something and still feel tense, empty, or unable to fully enjoy it. A kinder strategy is to integrate pleasure into the achievement process—micro-rewards, recovery cycles, and enjoyment of mastery and progress, not only the finish line. Then pleasure supports performance as maintenance, rather than becoming something you must endlessly “deserve.”`,
    Care: `You may strive to provide, protect, or stabilize loved ones—using achievement to secure resources and reduce uncertainty for the people you care about. In this pattern, care can start to feel tied to performance: “If I succeed, everyone will be okay.” The strain arises when relational safety still feels shaky despite your effort, which can push you into carrying more than your share. A healthier balance is to separate care from over-functioning: keep contributing, but also invite shared responsibility, direct communication, and emotional reciprocity. Care isn’t only what you deliver—it’s also what the relationship can hold with you.`,
    Affiliation: `You may use achievement as a pathway to belonging—hoping success will bring approval, admiration, or inclusion. This can make connection feel conditional: you feel closer when you’re “winning” and more anxious when you’re not. The strain often shows up as social insecurity or impostor feelings, where relationships feel fragile because they depend on performance. A steadier balance is to pursue affiliation directly through shared time, mutual support, and selective vulnerability—ways of being known beyond your results. Achievement can complement belonging, but it can’t replace the felt safety of being accepted as a whole person.`,
    Value: `You may treat achievement as moral validation—believing that being productive or excellent proves you are worthy and “good.” When outcomes don’t deliver that inner confirmation, the strain can feel personal and heavy, as if a missed goal means you failed as a person. This often intensifies when goals don’t match your genuine interests, your real strengths, or the environment you’re in. A healthier approach is to define “valuable goals” using your internal compass—your genuine interest, competence, and environmental support—while separating dignity from output. Then achievement can serve your values without becoming your identity or your scoreboard of worth.`,
  },

  Dominance: {
    Exploration: `You may push for control first so you feel safe enough to explore later—treating uncertainty as something you must neutralize before curiosity is allowed. This can quietly trap you in “management mode,” where you keep stabilizing the environment but never feel free enough to experiment. The strain shows up as rigidity and mental narrowing; exploration starts to feel risky instead of energizing, so you postpone it again and again. A healthier balance is to create bounded exploration: small experiments with clear limits, low stakes, and defined time windows. This lets curiosity return without requiring total control, and it often builds confidence that uncertainty can be handled rather than eliminated.`,
    Achievement: `You may rely on force, urgency, or pressure on others (or yourself) to support performance—using dominance as a motivational engine. It can work in the short term, especially when you need quick movement, but it often becomes draining because you have to keep escalating intensity to maintain momentum. The strain can show up as conflict, fatigue, or a sense that life is always a contest where you must “push” to get outcomes. A more sustainable path is to replace force with systems—routines, feedback loops, clear scope, and predictable milestones. When achievement is supported by structure instead of sheer intensity, progress becomes steadier and you don’t have to live in constant pressure.`,
    Pleasure: `You may pursue dominance to access pleasure—treating winning, control, or being “on top” as a substitute for relaxation and joy. The hope is that once things are under your command, you’ll finally feel free, but often the opposite happens: control keeps your nervous system vigilant. The strain is that pleasure stays shallow or rare, because your body remains in command mode even when you “have time.” A helpful balance is to practice pleasure that is explicitly non-competitive and non-instrumental—rest, play, softness, sensory comfort, or quiet enjoyment that doesn’t prove anything. Pleasure becomes more available when it doesn’t require dominance to justify it.`,
    Care: `You may take charge in relationships to protect people or prevent chaos, hoping control will compensate for care anxiety. Over time, this can turn care into management—helping, fixing, advising, steering—rather than emotional attunement. The strain often appears as resentment (“I’m carrying everyone”) or disconnection (“I’m close, but not emotionally met”), because control can’t substitute for mutual warmth and responsiveness. A healthier approach is care with consent and collaboration: ask what support is wanted, share responsibility, and allow others their autonomy. Care is often satisfied most deeply through trust and partnership—not only through control.`,
    Affiliation: `You may seek status or authority to secure belonging—assuming that if you’re important, you won’t be excluded. That can create relationships that feel transactional, where affiliation depends on role, usefulness, or rank rather than genuine closeness. The strain is “loneliness at the top”: you may be surrounded by people yet still feel unseen or unsupported. A steadier balance is to invest in horizontal bonds—friendship, shared identity, reciprocity, and moments of mutual vulnerability. Affiliation becomes more stable when you don’t have to perform dominance to keep your place.`,
    Value: `You may enforce rules or certainty to feel morally aligned—using dominance to make the world match what you believe is right. The strain shows up when reality resists: you can’t fully control others’ choices, so frustration builds and the system feels perpetually “not corrected enough.” This can harden into rigidity or constant judgment, which is exhausting and often isolates you from nuance and connection. A healthier approach is to focus on high-leverage principles and influence through modeling, persuasion, and boundaries rather than force. Values become more sustainable when you can practice them consistently without needing total compliance from the world.`,
  },

  Pleasure: {
    Exploration: `You may reach for quick stimulation when curiosity feels blocked—using pleasure as a retreat from frustrations around exploration. The tricky part is that too much stimulation can actually make real exploration harder by fragmenting attention and lowering tolerance for slow, effortful learning. The strain can become a restless loop: you keep sampling novelty, but rarely get the depth that truly satisfies curiosity. A more supportive balance is to reduce noise and create low-stimulation exploration—slow reading, long walks, reflective learning, or hands-on tinkering without pressure. When pleasure becomes calmer and more regulating, exploration tends to feel more meaningful and rewarding again.`,
    Achievement: `You may lean on mood and rewards to get yourself moving—using pleasure as a motivational hack to push productivity. When structure or competence isn’t in place, rewards don’t reliably translate into progress, and that can leave you feeling guilty or stuck. The strain can sound like: “I need to feel good to work, but I need to work to feel good.” A healthier approach is to build minimum-viable routines—small daily actions that happen regardless of mood, so progress is steady and predictable. Then pleasure becomes reinforcement after effort, not the engine that effort depends on.`,
    Dominance: `You may use indulgence as an escape when you feel frustrated about control, influence, or direction—turning pleasure into relief from the stress of not being able to steer things. This can create an uncomfortable cycle of escape and regret, where the underlying need for direction remains unresolved. A steadier balance is to separate the two: protect genuine time for relaxation, while also reserving focused time to rebuild a sense of control where it’s actually possible. That might look like learning group dynamics, doing background research, or preparing better—so you can steer the parts of your environment that can be influenced. Pleasure then becomes restorative, while dominance becomes more grounded and less reactive.`,
    Care: `You may use comfort to compensate for strain in intimate relationships—soothing yourself or others when deeper emotional needs aren’t being met. The strain is that pleasure becomes a band-aid and an escape: it can reduce discomfort short-term, but it doesn’t reliably create bonding, consistency, or intimacy. A balanced strategy is to pair pleasure with relational care behaviors—checking in, showing up consistently, offering direct support, and having repair conversations when needed. Then pleasure supports care instead of replacing it, and closeness becomes more stable over time.`,
    Affiliation: `You may seek fun social experiences to compensate for loneliness. If what you truly need is deeper affiliation—acceptance, loyalty, being known—then “fun” can sometimes leave you emptier afterward. The strain becomes social fatigue without real closeness. A healthier approach is to shift from event-based connection to relationship-based connection: recurring contact with fewer people, more depth, and more honest sharing. Pleasure becomes a bonus that enriches belonging, rather than the main route you have to rely on.`,
    Value: `You may use pleasure as an escape from feelings of worthlessness, or to quiet inner “shoulds” and moral pressure. If your value system is rigid, pleasure can carry guilt, which prevents it from restoring you the way it’s meant to. The strain often looks like oscillation between discipline and indulgence. A better balance is to update your values to include rest as responsible and pleasure as maintenance—not moral failure. When values become kinder, pleasure becomes cleaner, and you get both relief and integrity at the same time.`,
  },

  Care: {
    Exploration: `You may invest deeply in caring for others, hoping the relationship will also bring you learning, novelty, or a sense of growth—perhaps through admiration of your partner’s exploratory strengths, or as comfort after frustrating exploration experiences. Still, your need for exploration is personal and can’t be fully fulfilled through someone else, even someone you love. When the relationship becomes consuming, your curiosity may quietly fade, and you can start to feel mentally boxed in or stagnant. The strain is that care becomes the whole identity, while curiosity begins to feel selfish or unsafe to pursue. A healthier balance is to protect personal exploration time as part of being a good caregiver, not in conflict with it—when your mind is nourished, your care becomes more generous, steady, and less vulnerable to resentment.`,
    Achievement: `You may pour a lot of energy into building and supporting intimate relationships, hoping closeness will soothe frustration around achievement and progress. Yet relationships can’t replace the specific satisfaction that comes from competence, mastery, and finishing goals—so the underlying achievement tension can remain. The strain often shows up as over-investing in caretaking while feeling quietly disappointed about your own forward motion. A balanced approach is to keep care as a strength, while also reserving protected time for direct achievement practices: clear goals, small wins, and environments that reward progress. When achievement is addressed directly, care no longer has to “carry” what achievement is meant to resolve. Then your relationships become a supportive base, not a substitute.`,
    Dominance: `You may care in a way that tries to prevent harm by controlling outcomes—helping, fixing, managing, advising, and steering. This often comes from a protective instinct and the worry that “If I don’t guide this, something will go wrong.” The strain is that care becomes heavy: you get exhausted, and resentment can build, especially if others feel managed rather than supported. Over time, this can also create relational distance, because control reduces the sense of mutual trust. A healthier balance is to shift from control-care to choice-care: offer support, ask permission, and allow others to own their decisions and consequences. When care doesn’t require dominance, it becomes lighter, more respectful, and more sustainable.`,
    Pleasure: `You may give care hoping it will create warmth, peace, or emotional safety that also makes up for your own unmet pleasure needs. If others don’t reciprocate—or if the relationship stays stressful—you can end up deprived on both fronts. The strain is a quiet depletion: you keep supporting loved ones, yet the care may feel overwhelming to them, and the warmth you need doesn’t reliably come back. Pleasure then becomes something postponed “until everything is okay,” which rarely arrives. A better approach is to treat pleasure as a legitimate requirement and schedule it explicitly—small, regular sources of enjoyment that don’t depend on others’ moods. When your own pleasure is met, care becomes sustainable rather than sacrificial, and it’s often received more positively too.`,
    Affiliation: `You may care partly to secure belonging—becoming indispensable so you won’t be excluded or forgotten. This can turn care into a strategy for safety rather than a natural expression of connection, and you may feel anxious when you’re not needed. The strain is conditional belonging: affiliation starts to feel like it depends on your usefulness. Over time, this can limit your freedom and make relationships feel subtly transactional, even if you have good intentions. A healthier balance is to practice affiliation directly through mutuality—sharing needs, asking for support, and letting others contribute. Belonging becomes stronger when care flows both ways, and you feel valued for who you are, not only for what you provide.`,
    Value: `You may spend a lot of energy maintaining intimate relationships out of duty—trying to prove you are good, responsible, or morally aligned. If your value system is demanding, care can become heavy, and setting limits may trigger guilt, as if boundaries mean you’re failing. The strain is chronic over-commitment and self-neglect framed as virtue, where “being good” quietly becomes exhausting. A healthier approach is to broaden what “goodness” means to include sustainability, rest, and honest limits. When you allow care to be wise rather than endless, it becomes a cleaner expression of your values—one that strengthens relationships instead of draining you.`,
  },

  Affiliation: {
    Exploration: `You may seek social connection as a gateway to innovation—feeling that relationships with people who carry novel ideas can offer inspiration, resources, or support for your own exploratory endeavors. If the group isn’t stimulating or you feel a bit insecure, exploration can slow down, and you may find yourself experimenting with different circles or activities in search of the right fit. The strain is that curiosity can start to depend on external validation and social energy. A healthier balance is to cultivate solo exploration alongside shared experiences. When exploration isn’t socially contingent, affiliation becomes a choice rather than a necessity.`,
    Achievement: `You may invest in belonging to a group to increase your chances of achievement, seeking resources, support, reassurance, approval, or encouragement. The strain is that social time can unintentionally replace the tasks that would actually resolve achievement dissatisfaction directly and more effectively. A balanced approach is to use affiliation as additional support for execution: reliable partners, collaborative goals, and structured encouragement. Belonging can aid achievement, but never replace it.`,
    Dominance: `You may try to secure belonging to fulfill the need for gaining control—feeling that belonging can facilitate control. This can create tension because affiliation requires mutual respect rather than dominance. The effort to make social connections often requires one to relinquish impulses of dominance. A healthier approach is to separate domains of affiliation and dominance, don’t mix the two social settings as one. You can have your circles of friends where it focuses on mutual support, and another setting where you focus on being the decision maker.`,
    Pleasure: `You may socialize for relief and enjoyment, hoping fun can compensate for lack of pleasure and relaxing experience. However if connection requires effort to maintain, it can feel straining rather than relaxing. A healthier approach is to combine social pleasure with connections: choose the right kind of social group that make you feel more relaxed and less about fitting in.`,
    Care: `You may seek closeness to ensure care—assuming proximity will naturally create support. If others are present but not responsive in the way you need, affiliation may not satisfy care needs and can start to feel painful. The strain becomes confusion and disappointment: “We’re connected, so why don’t I feel cared for?” A healthier strategy is to make care explicit: ask directly, negotiate support, and choose relationships with reciprocity. Affiliation becomes most meaningful when it reliably carries care.`,
    Value: `You may feel that being included is an important part of feeling worthiness—so belonging becomes a signal that you are “on the right side” rather than a chance to enjoy friendship and peer support. This can create strain: you fit in a group, but don't genuinely feel that you are in the “right kind of group” in your own value system. A healthier approach is to clarify your principles and choose communities that match them, or create room for pluralism within relationships. Belonging is strongest when it doesn’t require self-erasure.`,
  },

  Value: {
    Exploration: `You have a value system that suggests if you follow a chosen path, you can create the right conditions to explore—new ideas, experiences, or identities that feel personally alive. The strain often comes from the fact that external value systems tend to reward “approved” exploration (safe, credentialed, easy to explain), while your real exploratory needs can be more unique, nonlinear, and intrinsically motivated. You may do everything you’re supposed to do, yet still feel hesitant, because no system can fully grant the inner permission that genuine exploration requires. As a result, exploration can start to feel stalled or strangely empty: you complied, but you don’t feel truly free. A healthier balance is to treat exploration as an essential internal nutrient—protect time for curiosity (hobbies, research, travel, creative play) and let outside values be a helpful reference, not the gatekeeper. Then value supports exploration without turning it into a monitored performance.`,
    Achievement: `You have a value system that suggests if you follow a chosen path, you can achieve goals that the system recognizes and rewards. The strain often comes from pursuing goals that are socially prestigious but not personally aligned, or from realizing you did everything “right” yet the system still doesn’t acknowledge your achievement in the way you expected. As a consequence, it’s understandable to feel disillusioned and frustrated. A healthier balance is to define “valuable achievement” in terms of your internal compass—your genuine interest, competence, and environmental support—while letting outside values remain a point of reference rather than the final judge of success. Then value supports achievement without becoming a confining cage.`,
    Dominance: `You have a value system that suggests if you follow a chosen path, you can justify taking control—setting direction, enforcing standards, or correcting what feels wrong. The strain often comes from trying to translate broad moral ideals into constant intervention in real life: the world doesn’t always cooperate, people may resist, and outcomes remain imperfect. You may do everything you feel you should do—set rules, push, manage, “hold the line”—yet reality still won’t fully align, which can be deeply tiring. As a result, dominance can become tense and exhausting: it can feel like you’re responsible for maintaining order everywhere, and your nervous system doesn’t get to fully relax. A healthier balance is to narrow the scope of what you must control: focus on boundaries, selective arenas of influence, and consistent modeling rather than total enforcement. Then value supports dominance without turning you into a full-time moral police force.`,
    Pleasure: `You have a value system that suggests if you follow a chosen path, you can finally deserve pleasure—rest, comfort, enjoyment—without guilt. The strain often comes from external standards that treat pleasure as suspicious or secondary, so even when you “earn it,” your body may not fully let you receive it. You may do everything you’re supposed to do, yet pleasure still feels diluted, rushed, or quietly restricted, as if relaxation is never completely allowed. As a result, you may swing between deprivation and binge-like relief: pleasure becomes a pressure valve rather than true replenishment. A healthier balance is to redefine pleasure as part of responsible functioning—small, regular enjoyment that sustains energy and reduces rebellion cycles. Then value supports pleasure without turning it into a reward you can never quite claim.`,
    Care: `You have a value system such that it seems if you act according to the rules, it will bring you closer to your loved ones and family. The strain often comes from the fact that what you sincerely believe is “good care” may not match what they actually need in the moment. A balanced approach is to stay grounded in your values while also listening more directly to their real needs—supporting them in the ways that truly land for them, not only in the ways your value system says you should provide. This can make your care feel more effective and more warmly received. In this way you support them in ways that help, while also avoiding over-giving that quietly drains your energy.`,
    Affiliation: `You have a value system such that it seems if you act according to the rules, it will bring you closer to a community—earning belonging through being “the right kind” of person. The strain often comes from the fact that what you think strengthens connection (correctness, loyalty, proving alignment) may not always serve what relationships and groups truly need (warmth, honesty, shared humanity, flexibility). As a result, you may keep investing in being acceptable yet still feel emotionally outside—because people connect most to your real presence, not your compliance. A balanced approach is to listen for the group’s real relational needs (trust, reciprocity, humor, vulnerability) and to choose contexts where difference is tolerated rather than punished. In this way you support affiliation in ways that actually create closeness, while also reducing the pressure to over-adapt to “rightness” in a way that violates your core beliefs.`,
  },
};

export const DRAIN_ADVICE_ZH: Record<DriveName, Partial<Record<DriveName, string>>> = {
  Exploration: {
    Achievement: `你可能在探索新想法和可能性上投入了很多心力，期待某个“关键洞见”能为你打开通往目标成就的大门。这种模式让你感觉富有产出，又不必面对目标常见的限制，比如截止日期、范围收窄，或接受不完美的执行。但问题在于，好奇心不断扩张，而“成就进度条”却迟迟未动，探索渐渐变成一种忙碌的杂事，而非真正的成长。更安心的平衡方式是保留探索的热情，同时习惯性地将它转化为一个具体的交付物，比如原型、草稿、投稿、演示，或一个可衡量的小里程碑。这样，探索就不再是绕开目标的岔路，而是推动目标前进的燃料。`,

    Dominance: `你可能部分是为了获得掌控感而探索新想法，相信“最有说服力的人”就能主导方向、拍板决策。这会让探索悄悄变成一种领导策略，用新奇见解来证明权威。但现实往往不可预测，即使你有很棒的想法，也可能依然感到焦虑，因为真正的“掌控局面”并未到来。更健康的做法是把洞见和控制分开，用探索找出那些你真正能影响的杠杆点，然后在那个范围内做出小而果断的行动。这样，探索就从对地位的追逐，转变为对自己选择更踏实的掌控感。`,

    Pleasure: `你可能用新鲜感和刺激来补偿难以获得的真正休息或娱乐享受。当放松似乎遥不可及时，探索就成了替代品，比如新主题、新计划、新的“兔子洞”，让你暂时避开无聊、空虚或疲惫。但久而久之，新鲜感不再修复你，反而变成一种关不掉的躁动。更支持性的平衡是主动安排“有意的娱乐享受”，比如感官舒适、自由玩耍、无目的的放空，或纯粹的恢复时间。当你把享乐视为正当需求，而不是必须“挣来”的奖励，探索才会重新变得快乐，而非强迫性的任务。`,

    Care: `你可能把大量精力投入到理解他人、心理学或关系动态中，希望“看懂了”就能弥补亲密关系中的未被满足，无论是伴侣还是家人。这容易形成“过度分析式照顾”，用思考代替直接的情感接触与修复。压力常出现在你觉得自己“都想明白了”，但关系依然缺少温暖、安全感或互惠的时候。更好的平衡是少一点解释，多一点简单的亲密守护行为，比如稳定出现、耐心倾听、温柔安抚，以及直接的支持行动。亲密关系往往更需要陪伴与可靠，而不是更多分析。`,

    Affiliation: `你可能把追求新体验和新想法当作建立人际关系的途径，希望自己有趣、见多识广或敢于冒险，就能自然获得连接。在这种模式里，探索成了社交的“货币”，你会觉得只要持续带来新鲜东西，就会被接纳。但亲近感其实更依赖重复、信任和共同投入，而非新鲜感。更稳的平衡是保留探索的热情，同时建立“归属仪式”，比如定期联系、共同承诺，或即使没有新话题也愿意彼此陪伴。这样，人际关系会变得更稳定、更安全，而不需要你不断表演。`,

    Value: `你可能有一套价值观，认为“有创意、爱探索”是一种珍贵特质，相信做一个“酷酷的创新者”能满足社会或家庭的期待。但当持续探索没有转化为符合你内在标准的结果时，你可能会开始怀疑自己，觉得只有产出“重大发现”才算有价值。这会让价值感绑定在“异常的原创性”上，门槛太高，也太耗人。更健康的平衡是重新思考，你是否必须不断创造新东西才有价值。其实，很多形式的贡献同样有意义，比如指导他人、精进手艺、提供服务、持续改进，或给予关系支持。它们都值得被看见，也值得被珍视。`,
  },

  Achievement: {
    Exploration: `你可能把追求目标成就当作“赢得探索资格”的方式，把好奇当作完成任务后的奖励，而不是日常的心理营养。这会让你即使在学习时也处于“表现模式”，而探索本该是恢复动力与清晰度的源泉。压力常表现为倦怠或麻木，你不断推进目标，但内心越来越干涸，灵感也越来越少。更支持性的平衡是把探索当作目标的输入，主动保护学习、实验和开放式好奇的时间。当探索被纳入日程，目标成就会更有创造力、更可持续，也不容易崩断。`,

    Dominance: `你可能通过追求成就来缓解无力感，相信成功会带来尊重、影响力或安全感。但这容易形成压力循环，越想掌控，就越押注结果，越不敢停下。问题是，成就很少带来持久的主导感，它给你短暂胜利，但底层的不确定感仍在。更健康的做法是在追求目标的同时，建立真实的能动性，明确权责、协商边界，聚焦在你真正有杠杆的领域。这样，掌控感来自清晰的结构与位置，而不只是结果本身。`,

    Pleasure: `你可能在目标成就上投入很重，期待它最终能带来平静、快乐，或“允许自己休息”的许可。但当享乐被推迟到“成功之后”，它往往永远不到来，因为总有下一个里程碑。压力可能表现为“快感缺失”，你完成了任务，却依然紧绷、空洞，难以真正享受。更温和的策略是把娱乐享受融入过程，比如小奖励、恢复周期，或享受掌握感与进步本身，而不只盯着终点线。这样，享乐成为支持表现的养分，而不是你必须“配得上”才能拥有的奢侈品。`,

    Care: `你可能努力提供资源、保护或稳定你在乎的人，用成就来降低他们的不确定性。在这种模式里，亲密守护和表现绑在一起，你会觉得只要我成功，大家就会安全。但即使你很努力，关系的安全感仍可能不稳，让你被推向承担更多。更健康的平衡是把亲密守护和过度负责分开，继续贡献，同时也邀请共同责任、直接沟通与情感互惠。亲密守护不只是你交付了什么，更是关系能否与你一起承载生活的重量。`,

    Affiliation: `你可能把成就当作获得归属的路径，希望成功能带来认可、赞赏或接纳。这会让连接变得有条件，顺境时更亲近，低谷时更焦虑。压力常表现为社交不安或“冒名顶替感”，因为关系似乎依赖表现而脆弱。更稳的平衡是直接经营人际关系，共享时间、互相支持、适度展现脆弱，让别人认识完整的你，而不只是你的成果。成就或许能加成归属，但无法替代“被整体接纳”的安全感。`,

    Value: `你可能把成就当作道德验证，觉得高产或优秀能证明你“是个好人”。当结果没带来内在确认时，压力会变得沉重，仿佛没达标就等于你这个人失败了。尤其当目标不符合你的真实兴趣、能力或环境时，这种负担更重。更健康的做法是用内在罗盘定义“有价值的目标”，关注真实兴趣、能力匹配与环境支持，同时把尊严和产出分开。这样，成就服务于你的价值观，但不会成为你的身份，更不是你的“价值计分板”。`,
  },

  Dominance: {
    Exploration: `你可能先追求掌控与主导，等“安全了”才允许自己探索，把不确定性当作必须先消除的威胁。这会悄悄把你困在“管理模式”里，不断稳定环境，却始终觉得没空间实验。压力表现为思维僵化、视野变窄，探索开始显得危险，而非充电，于是你一拖再拖。更健康的平衡是做“有边界的探索”，比如小实验、明确限制、低风险、固定时间窗口。这样，好奇心能自然回归，而无需彻底掌控一切。你也会逐渐相信，不确定性是可以处理的，不必被消灭。`,

    Achievement: `你可能依靠紧迫感、自我施压或推动他人来驱动表现，把主导当作达成目标的引擎。短期可能有效，尤其在需要快速推进时，但它往往更耗人，因为你必须不断加码才能维持动力。压力可能表现为冲突、疲劳，或感觉生活像一场永不停歇的比赛。更可持续的路径是用系统替代强推，建立例行机制、反馈回路、清晰范围和可预期的里程碑。当目标由结构支撑，而非靠意志硬撑，进展会更稳，你也无需长期活在高压中。`,

    Pleasure: `你可能通过掌控来换取享乐，把“赢”或“在顶端”当作放松的替代品。你希望一旦掌控局面就能自由，但常常相反，控制让神经系统更警觉。压力在于，享乐变得浅薄、稀少，因为即使你“有时间”，身体仍处于指挥模式。更好的平衡是练习“非竞争、非工具性”的享乐，比如休息、玩耍、感官舒适，或安静的独处，无需证明任何价值。当享乐不再需要主导来正当化，它才更容易自然发生。`,

    Care: `你可能在关系中通过掌控来保护他人或防止混乱，希望主导能缓解对亲密守护的焦虑。久而久之，守护变成管理，不断建议、修复、指挥，把方向牢牢握在手中。压力常表现为怨气，比如“我在扛所有人”，或疏离感，比如“我很近，但情感没被回应”，因为控制无法替代温暖与回应。更健康的做法是基于同意与协作的守护，先问对方是否需要，分享责任，允许对方自主。亲密守护往往通过信任与伙伴关系实现，而非控制。`,

    Affiliation: `你可能通过地位或权威来确保归属，觉得只要你重要，就不会被排除。但这会让关系变得交易化，归属依赖角色、有用性或等级，而非真实亲近。压力是“高处的孤独”，身边有人，却仍感到看不见、靠不住。更稳的平衡是投入平等的关系，比如友谊、共同身份、互惠支持，以及愿意展现脆弱的时刻。当你不必靠主导来保住位置，人际关系才会真正稳固。`,

    Value: `你可能用主导来执行规则，让世界更符合你心中的“正确”。但当现实不配合，比如他人不按你的标准行事，挫败会累积，系统似乎永远“不够好”。这可能让你变得僵化或持续评判，既耗心力，也削弱连接。更健康的做法是聚焦高杠杆的原则，并通过示范、说服与边界去影响，而非强制。道德价值在不需要世界完全服从时，才更可持续、更有人味。`,
  },

  Pleasure: {
    Exploration: `当探索受阻时，你可能用快速刺激来替代好奇，用娱乐躲开探索中的挫败。但刺激太多反而会切碎注意力，降低你对慢而深入学习的耐受力。压力变成一种躁动循环，不断尝鲜，却很少获得真正满足的好奇深度。更支持的平衡是降噪，尝试低刺激的探索，比如慢阅读、长散步、反思式学习，或无压力的手工实践。当享乐更平缓、更能调节身心，探索才会重新变得有意义，也更有回报。`,

    Achievement: `你可能用情绪和奖励来推动自己行动，把享乐当作促进行动的技巧。但如果缺乏结构或能力基础，奖励未必能稳定转化为进展，反而让你陷入内疚或停滞。压力常表现为“我得先感觉好才能工作，但我得工作才能感觉好”。更健康的做法是建立最低可行的例行机制，每天做一点点，无论心情如何，让进展稳定可预期。这样，享乐成为努力后的自然强化，而不是行动必须依赖的引擎。`,

    Dominance: `当你在主导、影响力或方向感上受挫时，可能用放纵来逃避压力，把享乐当作对“失控”的缓解。但这容易形成“逃避—后悔”的循环，底层的方向需求仍未解决。更稳的平衡是把两者分开，保护真正的放松时间，同时也留出专注时间，去重建你能掌控的部分，比如理解群体动态、做背景研究、充分准备，推动你真能影响的环节。这样，享乐更修复，主导也更踏实，而非反应式的挣扎。`,

    Care: `你可能用舒适来补偿亲密关系中的压力，在深层情感需求未被满足时，用享乐安抚自己或对方。但享乐容易变成创可贴，短期缓解不适，却无法带来稳定的依恋、安全感或亲密。更平衡的策略是把享乐与亲密守护行为配对，比如主动问候、稳定出现、直接支持，或在需要时开启修复对话。这样，享乐支持守护，而非替代它，关系也会更稳固。`,

    Affiliation: `你可能用好玩的社交来缓解孤独。但如果你真正渴望的是更深的连接，比如被接纳、被忠诚对待、被真正了解，“好玩”有时反而让你事后更空。压力表现为社交疲劳却无真正亲近。更健康的做法是从“事件型连接”转向“关系型连接”，联系更少的人，但更稳定，分享更真实，也更深入。享乐成为归属的加分项，而不是你唯一依赖的路径。`,

    Value: `你可能用享乐来逃离无价值感，或压制内在“应该怎样”的道德压力。如果价值观过于严苛，享乐会带着愧疚，无法真正修复你。压力常表现为在纪律与放纵之间来回摆荡。更好的平衡是更新你的价值观，把休息视为负责，把享乐视为自我维护，而非道德失败。当价值更温和，享乐更纯净，你也能同时拥有放松与内心的完整。`,
  },

  Care: {
    Exploration: `你可能在照顾他人上投入很深，希望关系也能带给你新奇、学习或成长，也许是欣赏伴侣的探索特质，或把关系当作探索受挫后的港湾。但探索是你个人的需求，即使深爱对方，也无法完全靠他们替你满足。当关系占据全部空间，你的好奇心会悄悄减弱，甚至感到思维被框住、停滞。压力在于，亲密守护成了你的全部身份，而探索开始显得“自私”或“不安全”。更健康的平衡是把个人探索时间视为“好照顾者的一部分”来保护，它不是与守护冲突，而是滋养它。当你的心智被滋养，你的照顾会更慷慨、更稳定，也更少积累怨气。`,

    Achievement: `你可能把大量能量投入亲密关系，希望亲近能缓解你在目标成就上的挫败。但关系无法替代那种来自能力、掌握与完成目标的独特满足感，底层的张力仍可能存在。压力常表现为你在照顾上越投越多，却对自己停滞隐隐失望。平衡做法是保留亲密守护的优势，同时为直接的目标成就保留受保护的时间，设定清晰小目标、庆祝微小胜利、营造能奖励进步的环境。当目标被直接处理，亲密关系就不用“扛起”本该由成就解决的部分，而能成为你坚实的支持底座。`,

    Dominance: `你可能用“防止出事”的方式来照顾，通过控制结果来帮忙、修理、建议或指挥。这通常源于保护本能，以及“如果我不引导，就会出问题”的担忧。但压力在于，守护变重，你会累；若对方感到被管理而非被支持，怨气也会升起。久而久之，关系距离反而拉大，因为控制削弱互信。更健康的平衡是从“控制式照顾”转向“选择式照顾”，先问对方是否需要，提供支持，允许对方拥有自己的决定与后果。当守护不需要主导，它会更轻盈、更尊重，也更可持续。`,

    Pleasure: `你可能在付出守护时，期待它带来温暖、平静或情感安全，同时也补偿自己未被满足的享乐需求。但如果对方不回馈，或关系依然紧张，你可能两头落空。压力是一种安静的耗竭，你不断支持，对方却感到压力，而你需要的温暖也迟迟不来。享乐于是被推迟到“等一切都好了再说”，但那一天很少到来。更好的做法是把享乐视为正当需求，并明确排进日程，安排小而规律的快乐来源，不依赖他人的情绪。当你自己的享乐被满足，你的守护会更可持续，也更容易被积极接收。`,

    Affiliation: `你可能部分是为了确保归属而照顾，让自己变得不可或缺，这样就不会被排除或遗忘。这会让守护变成安全策略，而非自然的连接表达；当你不被需要时，你可能会焦虑。压力是有条件的归属，关系仿佛取决于你的有用性。久而久之，你的自由变小，关系也带上交易感。更健康的平衡是练习互惠的关系，表达自己的需要，请求支持，让别人也能为你付出。当守护双向流动，归属更稳，你也会因“你是谁”而被珍惜，而不只是因“你提供了什么”。`,

    Value: `你可能出于责任感在亲密关系中投入大量能量，想证明自己是好人、负责、或道德一致。但如果价值观要求过高，守护会变重，设限会引发愧疚，仿佛边界等于失败。压力会变成长期过度承诺与自我忽略，却被包装成美德，“当个好人”悄悄变得很累。更健康的做法是扩展“善良”的定义，把可持续性、休息与诚实边界也纳入其中。当你允许守护是智慧的，而非无尽的，它才能更干净地表达你的价值观，也真正加深关系，而不是耗尽你。`,
  },

  Affiliation: {
    Exploration: `你可能把社交当作探索的入口，觉得和有新想法的人在一起，能带来灵感、资源或支持，从而推动你的探索。但如果群体不够激发你，或你感到不安，探索可能变慢，你会不断寻找“更合适”的圈子。压力在于，好奇心开始依赖外部认可与社交能量。更健康的平衡是并行培养独自探索与共同体验。当探索不再绑定社交，人际关系就成为你主动的选择，而非必需的依赖。`,

    Achievement: `你可能为了更容易达成目标而投入归属感，寻找资源、支持、认可或鼓励。但社交时间有时会无意中替代了那些更直接、更有效的行动。平衡做法是把人际关系当作执行的支持，比如可靠的伙伴、协作目标、结构化的鼓励。归属可以助力成就，但永远无法替代它。`,

    Dominance: `你可能希望通过归属来满足主导与控制的需求，觉得融入群体能增强掌控感。但这会产生张力，因为人际关系需要互相尊重，而非主导。建立连接往往需要放下控制冲动。更健康的做法是区分领域，你可以拥有以互惠为核心的朋友圈，也可以在其他场域专注做决策者。不把两种模式混在一起，关系和主导都能更自在。`,

    Pleasure: `你可能通过社交来获得放松与享乐，希望“好玩”能补偿缺少的休息。但如果维持连接需要太多用力，社交反而变成消耗。更健康的做法是选择让你真正放松的社交，那些不需要“表演融入”、能自然做自己的圈子。让享乐和连接真正融合，而不是彼此消耗。`,

    Care: `你可能以为靠得近，自然就能获得亲密守护。但如果对方“在场”却未以你需要的方式回应，关系就无法满足守护需求，甚至带来痛苦。压力表现为困惑与失望，“我们联系着，为什么我却不觉得被照顾？”更健康的策略是把需求说清楚，直接提出、协商支持、选择互惠的关系。人际关系最有意义的时候，是它能稳定地承载彼此的守护。`,

    Value: `你可能觉得被接纳是“你够好/有价值”的证明，于是归属更像是在确认你站在“正确一边”，而非享受友谊本身。这会带来压力，你融入了群体，却未必真心认同它的价值观。更健康的做法是澄清自己的原则，选择与之匹配的社群，或在关系中为多元留出空间。最强的归属，是不需要你抹去自己。`,
  },

  Value: {
    Exploration: `你相信只要走对路径，就能创造探索所需的条件，接触新想法、新体验，或活出更有生命力的身份。但外部体系往往只奖励“被认可的探索”，比如安全、正规、易解释的类型，而你真正的探索可能更独特、非线性，且由内在驱动。你做了所有“该做的事”，却仍犹豫，因为没有任何系统能完全授予探索所需的内在许可。于是探索可能停滞或变得空洞，你合规了，却不自由。更健康的平衡是把探索视为必需的内在营养，保护好奇时间，比如爱好、研究、旅行、创意玩耍，让外部价值只是参考，而非守门人。这样，道德价值支持探索，而不把它变成被监控的表现。`,

    Achievement: `你相信只要走对路径，就能实现被系统认可的目标。但压力常来自追求社会体面却与你内在不符的目标，或发现你做得“都对”，系统却未如预期回应。幻灭与挫败自然而来。更健康的平衡是用内在罗盘定义“有价值的成就”，关注真实兴趣、能力匹配与环境支持，同时把外部标准当作参考，而非最终裁判。这样，道德价值支持成就，而不成为束缚你的笼子。`,

    Dominance: `你相信只要走对路径，就能正当地取得主导权，定方向、立标准、纠正“不对”的事。但压力来自把宏大理想翻译成现实介入，世界不配合，人会抵抗，结果仍不完美。你做了所有“该做的”，现实却未对齐，这很累。主导于是变得紧绷、耗人，仿佛你要维持所有秩序，神经系统也难放松。更健康的平衡是收窄你必须控制的范围，专注边界、少数高影响场域、稳定示范，而非全覆盖执行。这样，道德价值支持主导，而不把你变成全职的道德警察。`,

    Pleasure: `你相信只要走对路径，最终就能“配得上”享乐，比如休息、舒适、快乐，而不带愧疚。但外部标准常把享乐看得可疑或次要，即使你“挣到了”，身体也未必允许你真正接收。你做了所有该做的，享乐却仍稀薄、匆忙，仿佛放松永远不被完全允许。于是你在剥夺与爆发式缓解间摆动，享乐变成泄压阀，而非真正补给。更健康的平衡是把享乐重新定义为负责运作的一部分，安排小而规律的享受，维持能量，减少反叛循环。这样，道德价值支持享乐，而不让它成为你永远领不走的奖励。`,

    Care: `你相信只要按规则行事，就能更靠近所爱之人。但压力常来自你真诚认为的“好照顾”，未必符合对方当下真正的需求。更平衡的做法是以价值观为根，但更直接地倾听他们的真实需要，用对他们真正有用的方式支持，而不只是按你的“应该”行事。这样，你的守护更有效，也更容易被温暖接收，同时避免在不知不觉中耗尽自己。`,

    Affiliation: `你相信只要按规则行事，就能融入某个社群，通过成为“正确类型的人”来赢得归属。但压力常来自你以为能增强连接的东西，比如正确、忠诚、一致，未必是关系真正需要的，比如温暖、诚实、共同人性、弹性。于是你不断努力被接受，却仍情感上在外，因为人更容易与真实的你连接，而非你的合规。更平衡的做法是听见群体真实的关系需求，比如信任、互惠、幽默、脆弱，并选择能容忍差异、而非惩罚差异的环境。这样，你用真正能带来亲近的方式支持关系，也减轻了为“正确”而过度适应、甚至违背核心信念的压力。`,
  },
};
export function getDrainAdvice(surfaceDrive: DriveName, innateDrive: DriveName) {
  return DRAIN_ADVICE[surfaceDrive]?.[innateDrive];
}

export function getDrainAdviceLocale(surfaceDrive: DriveName, innateDrive: DriveName, locale?: string) {
  const isZh = locale?.startsWith("zh");
  if (isZh) {
    return DRAIN_ADVICE_ZH[surfaceDrive]?.[innateDrive] ?? DRAIN_ADVICE[surfaceDrive]?.[innateDrive];
  }
  return DRAIN_ADVICE[surfaceDrive]?.[innateDrive];
}

